version: "3"

services:
  flask_app:
    build: .
    container_name: flask_app
    restart: always
    expose:
      - "5000"

  nginx_proxy:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask_app
