version: "3.9"

services:
  flask:
    build: .
    container_name: flask_app
    restart: always
    ports:
      - "5000:5000"
    networks:
      - flasknet

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask
    networks:
      - flasknet

networks:
  flasknet:
    driver: bridge
